CONSUMER_KEY : 'yE7vJQaPOx4NzYdDGdGj2z0Mu'
CONSUMER_SECRET : 'O6ziWt24NtwoowEuIE0ikJTuTuwDwkhlHPngz6AI1cutfCG4ZV'
ACCESS_TOKEN : '2916610206-J6yEm9PlkymrpztHx1URt9hJ5K4djgYw3UTns9r'
ACCESS_TOKEN_SECRET : 'O7keZ627dBQv1Cpbxh0BHGjBCS7VgKghwWkJG3iYsU4l0'
DEFAULT_USER_NAME : 'vivek8913'
